- src/main.ts
Small change to avoid duplicated `/auth` requests
Jira: https://easyemail.atlassian.net/browse/BACKEND-412
> Remove JWT refresh from the constructor

- package-lock.json
- package.json
- src/ApiModules/events.ts
Due to the fact that we want to track accepting ToS & Privacy Policy I'm adding `acceptedToS` event.
Change required by: https://github.com/PointMail/account-management/pull/63
> Add acceptedToS event

- package-lock.json
- package.json
- src/ApiModules/interactions.ts
Four interactions for the tutorial:
- **tutorialOpened**
- **tutorialStepViewed** (stores step number and an optional short description for the step - for our later reference)
- **tutorialFinished**
- **tutorialClosed**
> Add tutorial interactions

- src/authManager.ts
Autocomplete sessions creation will speed up.
> BACKEND-709 Call /init endpoint to pre-initialize

- package-lock.json
- package.json
- src/ApiModules/account.ts
- src/ApiModules/autocompleteSession.ts
- src/ApiModules/customSuggestions.ts
- src/ApiModules/interactions.ts
- src/__mocks__/authManager.ts
- src/authManager.ts
- src/index.ts
- src/main.ts
- src/pointApiBase.ts
I've implemeneted **AutocompleteSession** error handler so you can now register a listener for server errors `AutocompleteSession.setOnErrorHandler(callback)`. Right only one type of error is broadcasted:
- **exceeded_daily_usage_limit**
> BACKEND-730 API Daily Usage

- .github/pull_request_template.md
- README.md
- package-lock.json
- package.json
I've added **Deployment**  section in README.md as well as this nice PR template 🥇 
FYI merging this into master will result in a npmjs.com release 🙁 (but since I merged latest release it will not fail 🍀).
**The template will be available after merging to master - test if creating a new PR loads the template.**
- no
- no issue related
> Releasing is hell

- __mocks__/socket-mock.ts
- __tests__/main.test.ts
- src/ApiModules/autocompleteSession.ts
- src/Demo/autocompleteDemoSession.ts
> Set realtime data

- .vscode/settings.json
- __tests__/main.test.ts
- src/ApiModules/account.ts
- src/ApiModules/autocompleteSession.ts
- src/ApiModules/interactions.ts
- src/authManager.ts
- src/main.ts
- tslint.json
Introduces API versioning for api-autocomplete:
- Send **Accept** header with API version
- No
- Fixes https://easyemail.atlassian.net/browse/BACKEND-766
> BACKEND-766 api-autocomplete versioning

- src/ApiModules/account.ts
> 817 expand dropdown

- src/ApiModules/autocompleteSession.ts
- src/ApiModules/interactions.ts
- src/Demo/autocompleteDemoSession.ts
- Separate chosen hotkeys from suggestions
- Add chosenSuggestion interaction
- testing entire flow
- Fixes BACKEND-793
> BACKEND-793 chosen hotkeys

- __mocks__/socket-mock.ts
- __tests__/main.test.ts
- src/ApiModules/autocompleteSession.ts
> versioned feedback event

- .travis.yml
- .vscode/settings.json
- __mocks__/socket-mock.ts
- __tests__/main.test.ts
- package-lock.json
- package.json
- src/ApiModules/account.ts
- src/ApiModules/autocompleteSession.ts
- src/ApiModules/interactions.ts
- src/Demo/autocompleteDemoSession.ts
- src/authManager.ts
- src/main.ts
- tslint.json
> release 1.1.29 (API versioning, separate chosen hotkeys from suggestions in interactions, new realtime data)

- package-lock.json
- package.json
- src/Demo/authManagerDummy.ts
- src/__mocks__/authManager.ts
- src/authManager.ts
- src/main.ts
> Check if User is active

- src/ApiModules/customSuggestions.ts
> labels field

- src/ApiModules/account.ts
> Fix point search configs

- package-lock.json
- package.json
> lock down deps

- src/ApiModules/interactions.ts
- `pasteNotificationSave` interaction added
- `pasteNotificationDismiss` interaction added
- https://easyemail.atlassian.net/browse/BACKEND-981
- https://easyemail.atlassian.net/browse/BACKEND-982
- https://github.com/PointMail/scribe/pull/108
- https://github.com/PointMail/scribe/pull/109
- https://github.com/PointMail/account-management/pull/126
> BACKEND-981, BACKEND-982 Store interactions for paste notifications

- src/ApiModules/interactions.ts
- `showUseShortcutNotification` interaction added
- https://easyemail.atlassian.net/browse/BACKEND-976
- https://github.com/PointMail/scribe/pull/110
> BACKEND-976 showUseShortcutNotification interaction

- package-lock.json
- package.json
- src/ApiModules/interactions.ts
> notification interactions

- package-lock.json
- package.json
> Update all js-sdk dependencies & resolve issues (PR #69)

- __tests__/main.test.ts
- package-lock.json
- package.json
- src/Demo/localApiServer.ts
- src/Demo/pointApiDemo.ts
- src/Demo/suggestionsStore.ts
> PointApiDemo improved for the Tutorial (#71)

- src/Demo/suggestionsStore.ts
> about snippet

- src/Demo/localApiServer.ts
- src/Demo/suggestionsStore.ts
> debugging tutorial

- src/Demo/pointApiDemo.ts
- src/Demo/suggestionsStore.ts
> fix param order

- src/ApiModules/account.ts
- src/index.ts
- Add copy-paste notification enabled config
- Fix export for Website/WebsitePreferences interface
- https://github.com/PointMail/scribe/pull/139
- https://github.com/PointMail/api-autocomplete/pull/179
> BACKEND-1151 Add copy-paste notification enabled config

- package-lock.json
- package.json
- src/Demo/localApiServer.ts
- src/Demo/pointApiDemo.ts
- src/Demo/suggestionsStore.ts
- Update PointApiDemo with the latest changes
- Prepare PointApiDemo for Tutorial 2.0
> BACKEND-1123 Fix DemoApi for the new tutorial
